## Imports

In [12]:
import pandas, requests, json

## Load test data

In [21]:
with open('houston_zips.json', 'r') as f:
  houston_zips = json.load(f)
simple_shape = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "coordinates": [
          [
            [
              -111.96758627137338,
              33.503838484175375
            ],
            [
              -111.97904771486695,
              33.45763200126959
            ],
            [
              -111.92019150029336,
              33.46783861669121
            ],
            [
              -111.89234012644222,
              33.493246873827815
            ],
            [
              -111.92681699571692,
              33.5269288495591
            ],
            [
              -111.96758627137338,
              33.503838484175375
            ]
          ]
        ],
        "type": "Polygon"
      }
    }
  ]
}

## /data

In [ ]:
# Set up /data endpoint queries
queries = [
  {"buffer":0,"shape":json.dumps(houston_zips)}, # Zips in Houston
  {"buffer": 1, "shape": json.dumps(simple_shape), "geometries": True},
  {"buffer": 4, "sites": [{"lat":33, "lon":-112}]}, # A single set of coordinates
  {"buffer": 4, "sites": [{"lat":33, "lon":-112}, {"lat":34, "lon":-114}]}, # Two or more coordinates
  {"buffer": 0, "fips": ["482012301001","482012302002", "482012302003"], "scale":"blockgroup"}, # FIPS
  {"buffer": 0, "fips": "DE", "scale": "blockgroup"}, # One state, blockgroup level results
  {"buffer": 0, "fips": "DE", "scale": "county"}, # One state, county level results
  {"buffer": 0, "fips": ["DE", "RI"], "scale": "county"}, # Two states, county level results
]

In [37]:
# Execute /data endpoint
import time

for q in queries:
  time.sleep(5)
  try:
    url = "http://localhost:55001/data" #"https://ejamapi-84652557241.us-central1.run.app/data"
    response = requests.post(url, json=q)
    # Load response
    df = pandas.DataFrame.from_dict(response.json())
    display(df)
  except:
    print("error with ", q)

,EJAM Report,EJSCREEN Map,ejam_uniq_id,valid,pop,ST,statename,in_how_many_states,REGION,ratio.to.avg.Demog.Index,...,state.EJ.DISPARITY.traffic.score.supp,state.EJ.DISPARITY.pctpre1960.supp,state.EJ.DISPARITY.proximity.npl.supp,state.EJ.DISPARITY.proximity.rmp.supp,state.EJ.DISPARITY.proximity.tsdf.supp,state.EJ.DISPARITY.ust.supp,state.EJ.DISPARITY.proximity.npdes.supp,state.EJ.DISPARITY.drinking.supp,area_sqmi,geometry
0,"<a href=""https://ejamapi-84652557241.us-centra...","<a href=""https://pedp-ejscreen.azurewebsites.n...",1,True,123399.6,AZ,Arizona,1,9,0.8283,...,87.3294,72.9272,102.3956,68.2126,83.985,63.9312,99.9936,37.2937,32.4743,"{'type': 'Polygon', 'coordinates': [[[-111.967..."

,EJAM Report,EJSCREEN Map,ejam_uniq_id,valid,invalid_msg,pop,lon,lat,ST,statename,...,state.EJ.DISPARITY.rsei.supp,state.EJ.DISPARITY.traffic.score.supp,state.EJ.DISPARITY.pctpre1960.supp,state.EJ.DISPARITY.proximity.npl.supp,state.EJ.DISPARITY.proximity.rmp.supp,state.EJ.DISPARITY.proximity.tsdf.supp,state.EJ.DISPARITY.ust.supp,state.EJ.DISPARITY.proximity.npdes.supp,state.EJ.DISPARITY.drinking.supp,area_sqmi
0,"<a href=""https://ejamapi-84652557241.us-centra...","<a href=""https://pedp-ejscreen.azurewebsites.n...",1,True,,13841.5,-112,33,AZ,Arizona,...,18.0333,20.7834,16.4923,3.1568,1.8941,1.1838,29.8227,96.8384,102.757,50.2655

,EJAM Report,EJSCREEN Map,ejam_uniq_id,valid,invalid_msg,pop,ST,statename,REGION,ratio.to.avg.Demog.Index,...,state.EJ.DISPARITY.rsei.supp,state.EJ.DISPARITY.traffic.score.supp,state.EJ.DISPARITY.pctpre1960.supp,state.EJ.DISPARITY.proximity.npl.supp,state.EJ.DISPARITY.proximity.rmp.supp,state.EJ.DISPARITY.proximity.tsdf.supp,state.EJ.DISPARITY.ust.supp,state.EJ.DISPARITY.proximity.npdes.supp,state.EJ.DISPARITY.drinking.supp,area_sqmi
0,"<a href=""https://ejamapi-84652557241.us-centra...","<a href=""https://pedp-ejscreen.azurewebsites.n...",482012301001,True,,1380,TX,Texas,6,2.1126,...,215.4872,224.7555,208.5360,227.0726,125.1216,208.5360,192.3166,187.6824,0,0.5265
1,"<a href=""https://ejamapi-84652557241.us-centra...","<a href=""https://pedp-ejscreen.azurewebsites.n...",482012302002,True,,176,TX,Texas,6,2.1047,...,281.4480,272.4656,272.4656,290.4304,149.7064,275.4598,227.5537,251.5067,0,0.3791
2,"<a href=""https://ejamapi-84652557241.us-centra...","<a href=""https://pedp-ejscreen.azurewebsites.n...",482012302003,True,,1448,TX,Texas,6,2.1900,...,229.1651,216.9755,209.6617,234.0410,124.3343,226.7272,199.9100,204.7858,0,0.6477

## /query

In [34]:
# Set up and execute /query endpoint
import time

queries = [
  {"attribute": "pctunemployed", "value": .95}, 
  {"attribute": "o3", "value": .9},
  {"attribute": "no2", "value": .99},
  {"attribute": "pm", "value": .89},
]

for q in queries:
  time.sleep(5)
  try:
    url = "http://localhost:55001/query" #"https://ejamapi-84652557241.us-central1.run.app/query"
    response = requests.post(url, json=q)
    # Load response
    df = pandas.DataFrame.from_dict(response.json())
    display(df)
  except:
    print("error with ", q)

,bgfips,bgid,statename,ST,countyname,REGION,pop,Demog.Index,Demog.Index.Supp,pctlowinc,...,yesno_houseburden,yesno_transdis,yesno_fooddesert,pctlan_english,pctlan_french,pctlan_rus_pol_slav,pctlan_other_ie,pctlan_vietnamese,pctlan_other_asian,pctlan_arabic
0,010030115042,153,Alabama,AL,Baldwin County,4,1675,1.8984,2.3038,0.4484,...,0.0,1.0,1.0,0.89,0.00,0.0,0.01,0.00,0.00,0.0
1,010059501002,165,Alabama,AL,Barbour County,4,1378,2.2442,2.2745,0.4521,...,0.0,1.0,1.0,0.94,0.01,0.0,0.00,0.00,0.01,0.0
2,010059506001,177,Alabama,AL,Barbour County,4,473,3.6654,2.8366,0.8943,...,0.0,1.0,0.0,0.96,0.00,0.0,0.00,0.01,0.00,0.0
3,010070100051,188,Alabama,AL,Bibb County,4,1178,1.3713,2.4745,0.5289,...,0.0,1.0,0.0,0.94,0.00,0.0,0.00,0.00,0.00,0.0
4,010070100053,190,Alabama,AL,Bibb County,4,1995,0.6875,1.9129,0.2367,...,0.0,1.0,0.0,0.94,0.00,0.0,0.00,0.00,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12091,721537501022,242334,Puerto Rico,PR,Yauco Municipio,2,1818,3.2789,4.8276,0.7222,...,0.0,0.0,0.0,0.02,0.00,0.0,0.00,0.00,0.00,0.0
12092,721537502012,242336,Puerto Rico,PR,Yauco Municipio,2,1234,3.5634,4.9944,0.8436,...,0.0,0.0,0.0,0.10,0.00,0.0,0.00,0.00,0.00,0.0
12093,721537502021,242337,Puerto Rico,PR,Yauco Municipio,2,1224,3.5451,5.5610,0.8358,...,0.0,0.0,0.0,0.05,0.00,0.0,0.00,0.00,0.00,0.0
12094,721537502022,242338,Puerto Rico,PR,Yauco Municipio,2,1664,3.6050,5.0474,0.8707,...,0.0,0.0,0.0,0.05,0.00,0.0,0.00,0.00,0.00,0.0
12095,721537504004,242345,Puerto Rico,PR,Yauco Municipio,2,1554,3.5393,4.7322,0.8333,...,0.0,0.0,0.0,0.09,0.00,0.0,0.00,0.00,0.00,0.0

,bgfips,bgid,statename,ST,countyname,REGION,pop,Demog.Index,Demog.Index.Supp,pctlowinc,...,yesno_houseburden,yesno_transdis,yesno_fooddesert,pctlan_english,pctlan_french,pctlan_rus_pol_slav,pctlan_other_ie,pctlan_vietnamese,pctlan_other_asian,pctlan_arabic
0,040070005001,4721,Arizona,AZ,Gila County,9,2424,0.9472,2.1543,0.3366,...,0.0,1.0,0.0,0.95,0.0,0.0,0.0,0.0,0.01,0.0
1,040070005002,4722,Arizona,AZ,Gila County,9,3047,1.0956,2.1498,0.4022,...,0.0,1.0,1.0,0.95,0.0,0.0,0.0,0.0,0.01,0.0
2,040070006001,4723,Arizona,AZ,Gila County,9,854,1.5496,2.0491,0.5281,...,0.0,1.0,1.0,0.97,0.0,0.0,0.0,0.0,0.00,0.0
3,040070006002,4724,Arizona,AZ,Gila County,9,484,1.0772,1.9880,0.4401,...,0.0,1.0,1.0,0.97,0.0,0.0,0.0,0.0,0.00,0.0
4,040070007001,4725,Arizona,AZ,Gila County,9,1622,0.9513,2.9202,0.3884,...,0.0,1.0,1.0,0.98,0.0,0.0,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23817,551010029005,238107,Wisconsin,WI,Racine County,5,1220,1.8413,1.8634,0.4844,...,1.0,0.0,0.0,0.79,0.0,0.0,0.0,0.0,0.00,0.0
23818,551019900000,238109,Wisconsin,WI,Racine County,5,0,0.0000,0.3855,0.0000,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0
23819,551170011001,238438,Wisconsin,WI,Sheboygan County,5,1920,0.9269,1.5954,0.1995,...,0.0,0.0,0.0,0.85,0.0,0.0,0.0,0.0,0.09,0.0
23820,551170011002,238439,Wisconsin,WI,Sheboygan County,5,1707,1.2224,1.4912,0.2940,...,0.0,0.0,0.0,0.85,0.0,0.0,0.0,0.0,0.09,0.0
23821,551179900000,238481,Wisconsin,WI,Sheboygan County,5,0,0.0000,0.3855,0.0000,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.00,0.0

,bgfips,bgid,statename,ST,countyname,REGION,pop,Demog.Index,Demog.Index.Supp,pctlowinc,...,yesno_houseburden,yesno_transdis,yesno_fooddesert,pctlan_english,pctlan_french,pctlan_rus_pol_slav,pctlan_other_ie,pctlan_vietnamese,pctlan_other_asian,pctlan_arabic
0,010730027012,1371,Alabama,AL,Jefferson County,4,997,0.6601,1.6290,0.0963,...,0.0,0.0,1.0,0.98,0.0,0.0,0.01,0.0,0.0,0.0
1,010730027021,1372,Alabama,AL,Jefferson County,4,111,2.9588,3.5972,0.5856,...,0.0,0.0,1.0,0.96,0.0,0.0,0.00,0.0,0.0,0.0
2,010730027022,1373,Alabama,AL,Jefferson County,4,236,1.8338,2.7617,0.1314,...,1.0,1.0,1.0,0.96,0.0,0.0,0.00,0.0,0.0,0.0
3,010730027023,1374,Alabama,AL,Jefferson County,4,432,3.4900,3.3947,0.8264,...,0.0,0.0,0.0,0.96,0.0,0.0,0.00,0.0,0.0,0.0
4,010730027024,1375,Alabama,AL,Jefferson County,4,93,2.4942,3.6010,0.8387,...,0.0,1.0,1.0,0.96,0.0,0.0,0.00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2413,550250016042,235232,Wisconsin,WI,Dane County,5,2411,2.4558,1.7858,0.8632,...,1.0,1.0,0.0,0.90,0.0,0.0,0.02,0.0,0.0,0.0
2414,550250016043,235233,Wisconsin,WI,Dane County,5,624,1.6734,1.6290,0.5894,...,1.0,1.0,0.0,0.90,0.0,0.0,0.02,0.0,0.0,0.0
2415,721270091111,241903,Puerto Rico,PR,San Juan Municipio,2,1173,3.1188,3.9367,0.6539,...,0.0,0.0,0.0,0.11,0.0,0.0,0.00,0.0,0.0,0.0
2416,721270091112,241904,Puerto Rico,PR,San Juan Municipio,2,29,3.9299,4.0920,1.0000,...,0.0,0.0,0.0,0.11,0.0,0.0,0.00,0.0,0.0,0.0
2417,721270091113,241905,Puerto Rico,PR,San Juan Municipio,2,976,2.9479,3.3145,0.5809,...,0.0,0.0,0.0,0.11,0.0,0.0,0.00,0.0,0.0,0.0

,bgfips,bgid,statename,ST,countyname,REGION,pop,Demog.Index,Demog.Index.Supp,pctlowinc,...,yesno_houseburden,yesno_transdis,yesno_fooddesert,pctlan_english,pctlan_french,pctlan_rus_pol_slav,pctlan_other_ie,pctlan_vietnamese,pctlan_other_asian,pctlan_arabic
0,060014001001,11497,California,CA,Alameda County,9,1975,0.6626,0.6640,0.1028,...,1.0,1.0,0.0,0.78,0.02,0.01,0.05,0.00,0.02,0.02
1,060014001002,11498,California,CA,Alameda County,9,1294,0.7311,0.6756,0.0561,...,0.0,0.0,0.0,0.78,0.02,0.01,0.05,0.00,0.02,0.02
2,060014002001,11499,California,CA,Alameda County,9,948,0.4440,0.8218,0.0538,...,0.0,0.0,0.0,0.84,0.05,0.00,0.02,0.01,0.01,0.00
3,060014002002,11500,California,CA,Alameda County,9,1199,0.8959,0.9637,0.1243,...,0.0,0.0,0.0,0.84,0.05,0.00,0.02,0.01,0.01,0.00
4,060014003001,11501,California,CA,Alameda County,9,1300,0.7339,0.5142,0.0392,...,0.0,0.0,0.0,0.84,0.00,0.00,0.04,0.00,0.01,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26198,530779400061,233008,Washington,WA,Yakima County,10,2478,2.8094,2.4207,0.5721,...,0.0,1.0,0.0,0.26,0.00,0.00,0.00,0.00,0.00,0.00
26199,530779400062,233009,Washington,WA,Yakima County,10,2218,2.7616,2.8030,0.5081,...,0.0,1.0,0.0,0.26,0.00,0.00,0.00,0.00,0.00,0.00
26200,530779400071,233010,Washington,WA,Yakima County,10,1868,2.6749,2.6228,0.4739,...,0.0,1.0,1.0,0.26,0.00,0.00,0.00,0.00,0.00,0.00
26201,530779400072,233011,Washington,WA,Yakima County,10,1620,3.1984,3.1988,0.7012,...,0.0,1.0,0.0,0.26,0.00,0.00,0.00,0.00,0.00,0.00
26202,530779400081,233012,Washington,WA,Yakima County,10,2279,2.7906,3.0866,0.5649,...,0.0,1.0,1.0,0.28,0.00,0.00,0.00,0.00,0.00,0.00

## /report

In [10]:
# Set up report queries
queries = [
  #{"buffer":0,"shape":json.dumps(houston_zips)}, # Zips in Houston # too long a request?
  {"buffer": 1, "shape": json.dumps(simple_shape)}, 
  {"buffer": 4, "lat":33, "lon":-112}, # A single set of coordinates 
  {"buffer": 0, "fips": ["482012301001","482012302002", "482012302003"]}, # FIPS - will only do first in list 
  {"buffer": 0, "fips": "48201230100", "fileextension": "html"}, # Census Tract
  {"buffer": 0, "fips": "10001"}, # County
  {"buffer": 0, "fips": "44"}, # Single state FIPS
  {"buffer": 0, "fips": "4835000", "fileextension": "html"} # Place (Houston, TX)
]

In [11]:
# Report link constructor
# Creates and executes the query, but only outputs the url
import time

for q in queries:
  time.sleep(5)
  try:
    url = "http://localhost:55000/report" #"https://ejamapi-84652557241.us-central1.run.app/report" 
    response = requests.get(url, params=q)
    print(response.url)
    #print(response.text)
  except:
    print("error with ", q)

http://localhost:55000/report?buffer=1&shape=%7B%22type%22%3A+%22FeatureCollection%22%2C+%22features%22%3A+%5B%7B%22type%22%3A+%22Feature%22%2C+%22properties%22%3A+%7B%7D%2C+%22geometry%22%3A+%7B%22coordinates%22%3A+%5B%5B%5B-111.96758627137338%2C+33.503838484175375%5D%2C+%5B-111.97904771486695%2C+33.45763200126959%5D%2C+%5B-111.92019150029336%2C+33.46783861669121%5D%2C+%5B-111.89234012644222%2C+33.493246873827815%5D%2C+%5B-111.92681699571692%2C+33.5269288495591%5D%2C+%5B-111.96758627137338%2C+33.503838484175375%5D%5D%5D%2C+%22type%22%3A+%22Polygon%22%7D%7D%5D%7D
http://localhost:55000/report?buffer=4&lat=33&lon=-112
http://localhost:55000/report?buffer=0&fips=482012301001&fips=482012302002&fips=482012302003
http://localhost:55000/report?buffer=0&fips=48201230100&fileextension=html
http://localhost:55000/report?buffer=0&fips=10001
http://localhost:55000/report?buffer=0&fips=44
http://localhost:55000/report?buffer=0&fips=4835000&fileextension=html